### ISSUE TITLE
Add support for system ffmpeg and youtube-dl on Linux distros

### ISSUE THREAD

**Issue by ongun-kanat** [subhra74/xdm#10]
Almost all popular distros provide ffmpeg and youtube-dl. XDM should be able to use them instead of asking to download them.

**Comment by subhra74** [comment]
XDM bundles ffmpeg and youtube dl in its installer. There is no need for separate install. Although all distro provides the packages, they might not be latest or compatible with XDM. That's the reason for bundling them.

**Comment by ongun-kanat** [comment]
Both ffmpeg and youtube-dl have pretty standard interfaces for normal cases. However they can be optimized and hardware acceleration options can be added. You can always fallback to your own executables

**Comment by candrapersada** [comment]
add menu for update ffmpeg and youtube-dl
