### ISSUE TITLE
No DOWNLOAD VIDEO popup on Opera GX

### ISSUE THREAD

**Issue by cpatafio** [subhra74/xdm#100]
## Checklist

- [x ] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

I've been using XDM for several years without issue. I love it! However, today, I downloaded & installed the latest version of XDM (2020). I use Opera GX as my main browser. However, after installing the extension for Opera, the DOWNLOAD VIDEO popup is NOT appearing. Why?

**Comment by subhra74** [comment]
Is normal downloads being captured by xdm?

**Comment by cpatafio** [comment]
Hi Subhra…

Thanks for getting back so quickly.

To answer your question, yes. In other browsers, like Chrome, Firefox, Edge, even Opera, everything works fine including the DOWNLOAD VIDEO button appearing. It’s only in the new version of Opera, Opera GX, that the DOWNLOAD VIDEO button does not appear.

In Opera GX, I can still download the video by copying the video’s URL into the Download Video page on the XDM 2020 page. The only issue I’ve seen with XDM 2020 is the missing DOWNLOAD VIDEO button only in Opera GX.

Thanks for your help, Subhra!

Clem

**Comment by subhra74** [comment]
What happens if you click on the xdm icon in opera gx?
![image](https://user-images.githubusercontent.com/8403090/78725476-ee7fd400-792f-11ea-803a-dd25d1006d6c.png)

**Comment by cpatafio** [comment]
Hi Subhra,

When I left-click, nothing happens. When I right-click, I get a dropdown that only has 2 options… “Hide from toolbar” and “Manage extension…”, nothing more. I never see any dropdown listing the videos available for download.

As I mentioned in my first email, I can copy and paste the page link into the “Download Video” page opened from the XDM 2020 dashboard page. That usually works (not always).

Thanks for your prompt responses, Subhra.

Stay safe,

Clem Patafio

**Comment by cpatafio** [comment]
Hi Subhra,

I got it to work! I went to the Tools>Browser Monitoring page in the XDM 2020 dashboard and selected the second link (https://subhra74.github.io/xdm-firefox/chromium.html) in the "Chromium based browser" link. As soon as i selected the "Chrome Store" link on the page that appeared, the DOWNLOAD VIDEO popup appeared on the page and the XDM Manager link on the browser went from a B&W outline to a full-color link with a different dropdown (Browser Monitoring checkbox).

Thanks for all your help!!!

Stay safe...

Clem Patafio

**Comment by nino9** [comment]
I am using regular Opera (not GX) and cannot get the add on to install.
https://subhra74.github.io/xdm-firefox/chromium.html is also not resolved anymore.

**Comment by subhra74** [comment]
Please use the chrome extension:
https://chrome.google.com/webstore/detail/xtreme-download-manager/dkckaoghoiffdbomfbbodbbgmhjblecj

**Comment by MishimaPizza** [comment]
the chrome extension doesnt work either for even regular opera

**Comment by MakiseKurisuTina** [comment]
> Please use the chrome extension: https://chrome.google.com/webstore/detail/xtreme-download-manager/dkckaoghoiffdbomfbbodbbgmhjblecj

Chrome extension link is no longer resolved.
