### ISSUE TITLE
XDM doesn't get the download filename from `Content-Disposition` anymore

### ISSUE THREAD

**Issue by barraIhsan** [subhra74/xdm#1038]
**Describe the bug**
For example, if you download file from github, the default file name would be random string of letter and number, because the path is lead to that random string. Previous version of XDM Experimental (8.0.18) doesnt affect this bug. XDM should get the download file name.
[subhra74/xdm-experimental-binaries#48](https://github.com/subhra74/xdm-experimental-binaries/issues/48)

**To Reproduce**
1. Go to any download that the url and the filename is different (example, github releases https://github.com/subhra74/xdm/releases/)
2. Click on `xdmsetup-8.0.26.msi` 
3. See `0c88b896-5f2c-40e3-b0e1-09bb62705f23` in the filename

**Expected behavior**
see `xdmsetup-8.0.26.msi`

**Screenshots**
![image](https://user-images.githubusercontent.com/57800056/235856923-8338b625-a695-415c-9f08-317dfea19585.png)

**please complete the following information:**
 - OS: Windows 11
 - Browser Firefox
 - XDM addon Version 3.4
 - XDM Version 8.0.26 BETA

**Generated log using below method**
- (App from microsoft store)

**Additional context**
Download File Name is in `Content-Disposition`
![image](https://user-images.githubusercontent.com/57800056/235856982-1e8be344-1519-4e7c-9ef3-f953c670d9f9.png)

**Comment by madgoatz** [comment]
the solution is listed under this comment https://github.com/subhra74/xdm/discussions/768#discussioncomment-5281678

- just click download and it will automatically add the filename after

**Comment by barraIhsan** [comment]
> the solution is listed under this comment [#768 (comment)](https://github.com/subhra74/xdm/discussions/768#discussioncomment-5281678)
> 
>     * just click download and it will automatically add the filename after

oh, it confueses me up. Yeah, just click the download now 👍
