### ISSUE TITLE
Why is "Download Video" notification popping up constantly

### ISSUE THREAD

**Issue by Th3-A6add0n** [subhra74/xdm#1051]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

**Current version:** 8.0.26 BETA
**How to replicate the problem:** Just hover over any video on the YouTube home page.

Why is the "Download Video" notification popping up constantly by just hovering over the video thumbnails on YouTube?
Here's the [screen recording](https://ibb.co/QndG31r). The notification you see in that screen recording kept going on for a few minutes, even while I was writing about this issue here. This is really annoying.

Also, there are always 2 notifications for 1 YouTube video. (this means whenever I click on a YouTube video to watch it, there are always 2 notifications suggesting to download.) 

PS: The previous hovering button method (< v7.2.11) was way less annoying

**Comment by madgoatz** [comment]
![image](https://github.com/subhra74/xdm/assets/88365986/d22a882b-b037-42c9-98d8-6575b4d77b10)

open xdm settings -> Browser Monitoring -> then uncheck that thing as in the screenshot

**Comment by Th3-A6add0n** [comment]
> ![image](https://user-images.githubusercontent.com/88365986/239077263-d22a882b-b037-42c9-98d8-6575b4d77b10.png)
> 
> open xdm settings -> Browser Monitoring -> then uncheck that thing as in the screenshot

So you're telling me to turn the "feature" off & turn in on when I actually need it.
Wow.
What's the point of having it installed again?
Tbh, it's not like I'm asking something impossible here, previous extension, the hovering one, didn't do annoying notifications.

**Comment by madgoatz** [comment]
![image](https://github.com/subhra74/xdm/assets/88365986/918e3a20-0781-4cd0-865b-be082660af58)

pin the extension on your browser bar and click that to download videos

**Comment by madgoatz** [comment]
that last screenshot is XDM as well...

use whatever it is you want

**Comment by Th3-A6add0n** [comment]
> that last screenshot is XDM as well...
> 
I can see that, but what you're not seeing is that all of your "procedures" are not how XDM is supposed to work.

**Comment by madgoatz** [comment]
"XDM is still in beta"

**Comment by madgoatz** [comment]
well good luck using "DownThemAll" ✌️

**Comment by Th3-A6add0n** [comment]
> well good luck using "DownThemAll" ✌️

Hey @subhra74 does this guy even working on the project or just here to BS around? Because as far as I know, a project only flourishes when there are solutions to the problem not workarounds.

**Comment by madgoatz** [comment]
I think this issue should be closed.
