### ISSUE TITLE
XDM 8.0.26 BETA - option 'Get timestamp from server' has no effect

### ISSUE THREAD

**Issue by lkydev** [subhra74/xdm#1063]
### XDM is currently being re-written to be more user friendly and performant, please refer to (https://github.com/subhra74/xdm/discussions/768) for more information ###

**PLEASE DO NOT JUST SAY "It does not work, or something not working etc." Provide enough relevent details so that the issue can be analyzed and reproduced easily**

**Describe the bug**
With the said option checked, the modified timestamp of the downloaded file is not set to the 'Last-Modified' header provided by the web server.

**To Reproduce**
1. Enable the setting:

   a. Click hamburger menu -> Browser monitoring
   b. Scroll to the bottom
   c. Check 'Get timestamp from server'

2. Try to download a picture using XDM:

   a. Click New -> New Download
   b. Paste the url into the Address field: `https://www.debian.org/Pics/openlogo-50.png`
   c. Click 'Download Now'.

3. Using the command prompt, note the timestamp of the download:

   `powershell '(Get-Item "openlogo-50.png").LastWriteTimeUtc"`

4. From a command prompt, fetch the server timestamp:

   `curl -sI "https://www.debian.org/Pics/openlogo-50.png" | findstr /I Last-Modified`

**Expected behavior**
The download's timestamp (3) should agree with the server timestamp (4), but does not.

**Screenshots**

**please complete the following information:**
 - OS: [Windows 11 22H2 Pro]
 - Browser: Irrelevant
 - XDM addon Version: Irrelevant
 - XDM Version: 8.0.26 BETA

**Generated log using below method**
 - https://github.com/subhra74/xdm/wiki/Generate-log-for-troubleshooting

**Additional context**

**Comment by mvondev** [comment]
It is working on version 8.0.29 beta.
