### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ongun-kanat** [subhra74/xdm#11]
In what license do you share this source? I want to add some improvements but they may rely on (L)GPL sources.

**Comment by Kwaskoff** [comment]
> In what license do you share this source? I want to add some improvements but they may rely on (L)GPL sources.

where you see the code source?

**Comment by subhra74** [comment]
> In what license do you share this source? I want to add some improvements but they may rely on (L)GPL sources.

XDM is licenced under GPL.

**Comment by ongun-kanat** [comment]
@subhra74 can you put a license file

**Comment by Vascom** [comment]
As I see in GPLv3 text:
`...and give all recipients a copy of this License along with the Program`
So why you still not ship license file?

**Comment by subhra74** [comment]
When i will publish new release i will add it. By the way, Why does it matter anyway if you just want to add new changes?
