### ISSUE TITLE
Download the Chinese file, the file name will be garbled.

### ISSUE THREAD

**Issue by chenxinss** [subhra74/xdm#110]
Download the Chinese file, the file name will be garbled.

**Comment by vandpurnama** [comment]
it's a bug on xdm same reported issue #76 i got that problem too downloading file with korean or japanese language

**Comment by subhra74** [comment]
> it's a bug on xdm same reported issue #76 i got that problem too downloading file with korean or japanese language

@vandpurnama 
thanks

**Comment by ardypro** [comment]
It seems XDM support ASCII characters only

**Comment by subhra74** [comment]
The issue is with Java fonts, i am looking into it.

**Comment by objectProgrammer** [comment]
@subhra74 It's not related to fonts. Fonts are only used to display characters, if the font didn't support it would just show a square not garbled data. It's related to the url-decoding algorithm, which I've fixed in #394.
