### ISSUE TITLE
cant resume refresh link from google drive

### ISSUE THREAD

**Issue by 3xploiton3** [subhra74/xdm#112]
![image](https://user-images.githubusercontent.com/19517680/79050347-98729f80-7c53-11ea-8bf1-679cdfc58b33.png)

![image](https://user-images.githubusercontent.com/19517680/79050404-facba000-7c53-11ea-8e2c-5a351a208326.png)

**Comment by Josh-OS** [comment]
Hi, I have the same problem, not only in google drive but on another website, I also tried to paste the link in "Advanced Settings" but no avail.  The refresh link feature could be the best feature a download manager can have for downloads with a large file (in my opinion).

**Comment by vandpurnama** [comment]
it's bug with current version i already reported #58 i must downgrade xdm to 7.2.7 and waiting the issue to be fixed on next release

**Comment by subhra74** [comment]
Duplication of #58 
Bugfix will be provided on next release

**Comment by Josh-OS** [comment]
Hi @subhra74 I'm excited with the refresh link feature 😀

**Comment by Josh-OS** [comment]
@vandpurnama where can I get this version 7.2.7? The download available in the main page is 7.2.8, and those in the older release page were not labeled with their versions

**Comment by subhra74** [comment]
7.2.8 also should work

**Comment by 3xploiton3** [comment]
> 7.2.8 also should work

how to remove xdm 7.2.10 ?
i cannot overwrite with 7.2.8

**Comment by subhra74** [comment]
Please uninstall it from control panel/uninstall programs

**Comment by rohitidke** [comment]
This issue got resolved in new release 7.2.11. please close this issue @subhra74

**Comment by ArungAlam** [comment]
still bug in 7.2.1`

**Comment by Nur-A-Alam1997** [comment]
still bug in 7.2.11
