### ISSUE TITLE
After downloading file name becomes: UTF-8''file-name.rar

### ISSUE THREAD

**Issue by anburocky3** [subhra74/xdm#12]
After downloading some files from the internet through xtreme download manager. The file name is `UTF-8"file-name.rar` why is that so? Looks like an bug?

**Comment by subhra74** [comment]
yes its a bug. thanks for reporting

**Comment by lzzy12** [comment]
Any update on fix up of this bug?

> yes its a bug. thanks for reporting

**Comment by EgyptianM** [comment]
Any fix yet?

**Comment by subhra74** [comment]
Fixed

**Comment by anburocky3** [comment]
So should we update this software?

**Comment by subhra74** [comment]
Not yet, the issue is fixed in source, will publish the new release with this fix and several other fixes soon

**Comment by anburocky3** [comment]
Yes. Please :)
