### ISSUE TITLE
Browser monitoring for Brave brower

### ISSUE THREAD

**Issue by r7vv** [subhra74/xdm#1247]
I can't find the link for the extension.
The link in the app in invalid and leads to me a broken 404 website.
¯\_(ツ)_/¯

**Comment by inuonly** [comment]
https://github.com/subhra74/xdm/wiki/How-to-Install-Browser-extension-for-Google-Chrome---MS-Edge---Brave---Vivaldi-in-XDM-8

Hope this helps. My issue was solve by this which is available when I click chrome tab in browser addons option . My version is as follows.
![image](https://github.com/user-attachments/assets/90fca9d3-6abf-4e6a-a95c-1637bf0e671f)

**Comment by r7vv** [comment]
> https://github.com/subhra74/xdm/wiki/How-to-Install-Browser-extension-for-Google-Chrome---MS-Edge---Brave---Vivaldi-in-XDM-8
> 
> Hope this helps. My issue was solve by this which is available when I click chrome tab in browser addons option . My version is as follows. ![image](https://private-user-images.githubusercontent.com/26686197/361441970-90fca9d3-6abf-4e6a-a95c-1637bf0e671f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NzgyMjQsIm5iZiI6MTcyNDc3NzkyNCwicGF0aCI6Ii8yNjY4NjE5Ny8zNjE0NDE5NzAtOTBmY2E5ZDMtNmFiZi00ZTZhLWE5NWMtMTYzN2JmMGU2NzFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDE2NTg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkYzFlZmYxMTk4ODhlZWIzMDcxMGEwNTNmMzY3ZGM0NGEwOTExYzM1MzE2NjIyODViYzA5Nzk4MDc5MzY1NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.inJwidcYeC9hG7aeagsc9o7k8m-afvnuIy7dABJKFRM)

Thanks!
I got the latest beta version and had the extension 👍
