### ISSUE TITLE
Support plural sight downloading

### ISSUE THREAD

**Issue by tbhaxor** [subhra74/xdm#128]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running xdm latest version
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE

Is there any way to download videos from Pluralsight, for example, &rarr; https://app.pluralsight.com/library/courses/windows-internals2

The youtube-dl can find the link of the video but it breaks down and is frustrating.

**Comment by subhra74** [comment]
I will try to analyze, and if possible implement in future version
