### ISSUE TITLE
Download garbled characters with non-English characters

### ISSUE THREAD

**Issue by kofzhanganguo** [subhra74/xdm#143]
![image](https://user-images.githubusercontent.com/32073931/80630945-95671400-8a87-11ea-95c0-8f1406099b14.png)

Download garbled characters with non-English characters. For example, if I download a file with a Chinese file name, it will be garbled after downloading.

**Comment by Kristinita** [comment]
+1 for Cyrillic symbols:

![Cyrillic](https://i.imgur.com/di3u2Nb.png)

Thanks.

**Comment by objectProgrammer** [comment]
Fix waiting for merge at #394
