### ISSUE TITLE
XDM Needs Additional Components To Download This Video

### ISSUE THREAD

**Issue by oldgit77** [subhra74/xdm#145]
![image](https://user-images.githubusercontent.com/64638953/80799966-2a5d3080-8ba0-11ea-8b7a-e84094e6b76c.png)

![image](https://user-images.githubusercontent.com/64638953/80800044-60021980-8ba0-11ea-970a-fc533dc2d188.png)

XDM could not download the file as server sent an invalid response.

I hope you can help.

**Comment by subhra74** [comment]
Which XDM version are you using? Also Which installer?
Please provide all the details as mentioned in the issue template.

**Comment by oldgit77** [comment]
OS is Ubuntu 20.04 LTS Focal Fossa

Firefox Quantum. Installed as an extension. Chrome exhibits the same behaviour, as does the Java app.

![image](https://user-images.githubusercontent.com/64638953/80946002-ffafe980-8de4-11ea-91d6-d054363b9d11.png)

Hope this helps.

**Comment by oldgit77** [comment]
![image](https://user-images.githubusercontent.com/64638953/80946280-94b2e280-8de5-11ea-9320-db612c8a815e.png)

![image](https://user-images.githubusercontent.com/64638953/80946396-dc396e80-8de5-11ea-9033-d27be4b26bd2.png)

**Comment by subhra74** [comment]
what is the xdm version? is it XDM 2020? How did you installed it?

**Comment by oldgit77** [comment]
The plugin is Version 2.1 on both Firefox and Chromium 81.0.44.129.

I did also run XDM 2020 (Java runtime from terminal [ java - jar xdman.jar ]).

I get apparently identical issues.

XDM extension worked fine under Ubuntu 19.04 (I don't have the specifics to refer to since I replaced the OS with 20.04 LTS).

If there's anything you need, please let me know. This is a great piece of software. 

Regards

**Comment by AlSafty** [comment]
i have the same problem, i made an issue before reading this

**Comment by subhra74** [comment]
If you are using the jar only then please see:
https://github.com/subhra74/xdm/issues/155#issuecomment-626305892

**Comment by oldgit77** [comment]
I raised this issue for the extension. How would downloading (another?) copy of ffmpeg help in this case. ffmpeg is in my path and all packages/applications function as specified

**Comment by subhra74** [comment]
> 
> 
> I raised this issue for the extension. How would downloading (another?) copy of ffmpeg help in this case. ffmpeg is in my path and all packages/applications function as specified

There is no issue with extension. Only situation where additional component is needed to configure/installed when XDM is being run from Portable JAR only. 

XDM does not use PATH or installed packages for ffmpeg or youtube dl, because of version incompatibility problems. FFmpeg and Youtube dl executable binary must be present in either the directory where XDM jar is located or `~/.xdman/` directory. However if you want trouble free smooth installation please use the Linux installer, as it contains all necessary dependencies.

**Comment by oldgit77** [comment]
Thank you for your reply. I'm afraid there does appear to be an issue with the extension. This is why I raised the issue originally.

![evi1](https://user-images.githubusercontent.com/64638953/81638905-4f5c6980-9412-11ea-960d-a7881a3935d4.jpg)

![evi2](https://user-images.githubusercontent.com/64638953/81638927-60a57600-9412-11ea-9c9e-b91d1017e6fc.jpg)

**Comment by subhra74** [comment]
Are you getting the message after following the steps mentioned in previous comment?

**Comment by oldgit77** [comment]
Thank you. As advised I copied the ffmeg binary to the ~/.xdman/ folder. It now works.

Thanks again for your patience.
