### ISSUE TITLE
Ignoring My Ignore List 

### ISSUE THREAD

**Issue by rebeltaz** [subhra74/xdm#147]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I have tried adding www.foxnews.com, video.foxnews.com and foxnews.com to the "Do not automatically capture downloads from below web sites" list, but it is still popping up the [Download Video] button. With that site, even if I close the button, it keeps popping right back up! How do I tell XDM to stop that! 

App version 7.2.10 with runtime 11.0.6 on Linux with Firefox 75.0 (64-bit)

**Comment by subhra74** [comment]
Please refer #54

**Comment by rebeltaz** [comment]
I don't think that this is the same. I can close the popup. That's not the trouble. The problem is that I can't tell XDM to **not** display the popup at all on the foxnews website, even when it's specifically added to the "Do not automatically capture downloads from below web sites" list.

**Comment by subhra74** [comment]
That options is for intercepting downloads from browser. It does not prevent video monitoring. However adding to backlog to use the list to skip browser monitoring as well

**Comment by rebeltaz** [comment]
Well that explains that then doesn't it. Thank you for that. I appreciate it.
