### ISSUE TITLE
Cannot download YouTube video

### ISSUE THREAD

**Issue by nick51** [subhra74/xdm#150]
## Checklist

- [x ] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
I cannot download youtube video. I display video in browser then right-click and select 'Copy link address'. Using 'File/Add URL' in XDM, I paste this link and select 'Download Now'. The file that is downloaded is not the video, but a file named 'watch.html' with size 272kb. Can you tell me what I am doing wrong?

**Comment by subhra74** [comment]
Please use the `Download Video` menu item

![image](https://user-images.githubusercontent.com/8403090/80924885-0c542380-8d8c-11ea-8813-f31b7fca8e13.png)

**Comment by nick51** [comment]
Thank you. When I use the 'file/download video' option as suggested, the
program displays an input box with label 'find' next to it. What value
should I enter in that field? I tried copying the video link and pasting it
into that field and then clicking 'find', but nothing happens. Is there a
help file anywhere, that I could read?

**Comment by nick51** [comment]
Please ignore earlier email. I have managed to initiate download. Problem
was firewall. Seems to be working, so I can now test further. Also found
wiki for usage instructions. Thank you for this programme.
