### ISSUE TITLE
XDM chrome extension automatically disable the browser monitoring

### ISSUE THREAD

**Issue by darkshadow013** [subhra74/xdm#156]
## **XDM chrome extension automatically disable the browser monitoring even if it is enabled in app**

![Screenshot from 2020-05-08 12-15-39](https://user-images.githubusercontent.com/41981066/81378995-eaf58d80-9125-11ea-944e-fb7f74251cec.png)

 - OS: Linux
 - Browser: Chrome
 - XDM addon Version 2.1
- XDM Version 7.2.0

**See Browser Monitoring option and symbol of extension**
 - https://github.com/subhra74/xdm/wiki/Generate-log-for-troubleshooting

**Comment by subhra74** [comment]
Does restarting the browser works?

**Comment by darkshadow013** [comment]
No, It doesn't work.

**Comment by subhra74** [comment]
Are you using any VPN or proxy? If not please generate the log and share as mentioned in template
