### ISSUE TITLE
Folder "javasharedresources" is getting created repeteadly. 

### ISSUE THREAD

**Issue by abhishekruhela** [subhra74/xdm#161]
Folder "javasharedresources" is getting created repeteadly in Linux Mint 19.3 /home directory each time I open XDM 2020. This was not an Issue with 7.2.8. Everyting else seems to be working fine. The folder also contains a file named as: C290M11F1A64P_sharedcc_ab_G41L00. Here is the file properties. Please suggest something. Thanks a lot for creating this amazing piece of software :)

![image](https://user-images.githubusercontent.com/33756137/81667274-b43eb080-9460-11ea-9f7d-cc0cf406ab9c.png)

**Comment by subhra74** [comment]
This is a cache directory for the OpenJ9 java runtime ( java class files compiled to native code), that XDM uses. The cache improves XDM performance. In next XDM version the default location will inside $HOME/.xdman directory

**Comment by abhishekruhela** [comment]
Thanks a lot for your reply and help :)

**Comment by joe733** [comment]
> This is a cache directory for the OpenJ9 java runtime ( java class files compiled to native code), that XDM uses. The cache improves XDM performance. In next XDM version the default location will inside $HOME/.xdman directory

Just a friendly reminder... In version `7.2.11` it's still in the `$HOME` directory.

**Comment by subhra74** [comment]
Yea, it was missed in 7.2.11 :(
As an workaround you can modify the launcher script to prevent the location of the cache file in `/opt/xdman/xdman`
[https://github.com/eclipse/openj9-docs/issues/103](url)
[https://www.eclipse.org/openj9/docs/xshareclasses/](url)

**Comment by subhra74** [comment]
This will be fixed with the new release in October

**Comment by IEdiong** [comment]
Alright, thanks for the response.

**Comment by Macleykun** [comment]
Is this implemented in December :P ?

**Comment by AozoraDev** [comment]
Here's how i do it.

1. Open your terminal (of course)
2. `sudo nano /opt/xdman/xdman`
3. Add this after java `-Xshareclasses:cacheDir=~/.xdman/cache`
4.  Save it (Don't tell you don't know how to save file using Nano)

**Comment by swainasish** [comment]
@AozoraDev  It's working man, we are dumb, but fortunately we can handle this.

**Comment by Macleykun** [comment]
but how do this with sdkman?

**Comment by gituser23234235234887** [comment]
>     5. Add `-Xshareclasses:cacheDir=/home/<username>/.xdman/cache` to the xdman startup
what do you mean by "add to xdman startup"
I did step 3 and it seems to work. I could not figure out step 5.

**Comment by ghost** [comment]
> > ```
> > 5. Add `-Xshareclasses:cacheDir=/home/<username>/.xdman/cache` to the xdman startup
> > ```
> 
> what do you mean by "add to xdman startup" I did step 3 and it seems to work. I could not figure out step 5.

Me enither.
If step 3 works, then it works
