### ISSUE TITLE
file name of youtube video is weird

### ISSUE THREAD

**Issue by rinelfi-git** [subhra74/xdm#164]
Hi! I'm here for asking if there is a setting for video file from youtube which is comming with a slash. When I download a video file with a slash letter it is truncated.
How to avoid that or change the slash to underscore?

**Comment by subhra74** [comment]
It's a bug, as a workaround you can provide the file name manually till this is fixed.

**Comment by yzrsng** [comment]
I fixed it. #789
However, it would be better if users could set rules to convert invalid characters.
like to underscore,
like Hankaku to Zenkaku (!"#%*+/ → ！”＃％＊＋／)
