### ISSUE TITLE
[BUG] 720p youtube quality being ignored for download

### ISSUE THREAD

**Issue by Borwe** [subhra74/xdm#185]
**Describe the bug**
Cannot download 720p videos from youtube when 1080p exists as a youtube streamable option.

**To Reproduce**
1. Go to Any youtube video that has 1080p+ quality.
2. Click on 720p in youtube to download in that quality
3. Download button at corner once clicked, has no 720p option, but if you select any other quality it pops up.
4. Clicking even 1080p seems to available for download, everything but 720p.

**Expected behavior**
A download option for 720p to appear, once video starts streaming at that rate.

**Screenshots**
N/A

**please complete the following information:**
 - OS: Linux
 - Browser :Firefox
 - XDM addon Version: latest as of today.
 - XDM Version :7.2.10

**Additional context**
No such error when highest quality is a 720p Youtube video.

**Comment by subhra74** [comment]
Can you please provide the link for the video

**Comment by Borwe** [comment]
[Youtube Link](https://www.youtube.com/watch?v=ES1L2SPgIDI)

an example.

**Comment by biswasmoheshwar** [comment]
Go To Full Screen for 720 pixels download

**Comment by Borwe** [comment]
> Go To Full Screen for 720 pixels download

Yup, thanks works.

**Comment by biswasmoheshwar** [comment]
Welcome

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
