### ISSUE TITLE
How to convert from .ts to mp4 without altering any quality video?

### ISSUE THREAD

**Issue by candrapersada** [subhra74/xdm#188]
I just want to convert a .ts to .mp4, while maintaining quality. How can I do this? for example video 100MB .ts convert to .mp4 with the same video size 100MB

**Comment by subhra74** [comment]
size and quality are not comparable. using XDM it is not possible, but you can use ffmpeg which can convert it to MP4 without transcoding (meaning quality will not change)

**Comment by candrapersada** [comment]
and how to convert video from local file?

**Comment by subhra74** [comment]
Local files not possible

**Comment by ajie144** [comment]
Why is the video download in ts format in MP4 format and plays only sound but no video picture?
