### ISSUE TITLE
Video Converter is too slow.

### ISSUE THREAD

**Issue by biswasmoheshwar** [subhra74/xdm#199]
**Video Converter is too slow**

**To Reproduce**
1. Go to 'https://www.youtube.com'
2. Click on 'Download Video'
3. Select 360p
4. Convert to mp4 360p android/iphone
5. Click download now

 - OS: [Windows]
 - Browser [Chromium]
 - XDM addon Version [2.1]
 - XDM Version [7.2.11]

**Comment by subhra74** [comment]
video conversion is entirely dependent on ffmpeg and the selected codecs. XDM has no way of improvement here

**Comment by biswasmoheshwar** [comment]
ok
