### ISSUE TITLE
Rename before downloading looks not working

### ISSUE THREAD

**Issue by NEK-RA** [subhra74/xdm#202]
**Description:**
Sometimes we need to rename file before download, because their basic name is not uderstandable (or any other reason). It's the feature like the "Save as" and currently I never seen it's working.
 In the download dialog I see the link and the name for file that will be downloaded. I've changed the name from "Setup.exe" to "SqualrSetup.exe" to keep it understandable for me and start downloading. 
After finish I press "Open folder" and see that file downloaded with "Setup.exe" instead of custom name.
I've seen this problem in previous versions too - when I've tried to download the file with cyrrilic symbols in name, I've got encoded name, when I've tried to change the name before downloading result was the same. 

**To Reproduce**
1. Get link for the download
2. Add link to XDM
3. Change name before starting
4. Download the file
5. Open the folder and see that name was not changed

**please complete the following information:**
 - OS: Windows 10
 - Browser: Chromium based
 - XDM addon Version: 2.1 from Chrome Webstore
 - XDM Version: 7.2.10

**Generated log using below method**
Here is log and screen record
https://u.pcloud.link/publink/show?code=kZN7FtkZaqLhOmYsbAFEDLyxqQkRQYeqed77

**Comment by NEK-RA** [comment]
Sorry for reopening, I've missed the correct version number and wrote 7.2.0 instead of 7.2.10
Issue was edited to fix this mistake

**Comment by smhmd** [comment]
I second this. It broke my heart after preparing a gigantic queue to download (with kebab case of all naming conventions). I wanna sue, haha.

**Comment by JinstonC** [comment]
This issue still exists in 7.2.11
