### ISSUE TITLE
chrome-Browser-Extension link not working 

### ISSUE THREAD

**Issue by amangupta00** [subhra74/xdm#205]
i was trying a new distro , debian based, when i went to download the browser-extension it said 404 page not found .
This problem is just for chrome and chromium links , other platforms are working as before.

**Comment by CheneyYang** [comment]
The same thing happens with windows 10

**Comment by amangupta00** [comment]
@subhra74 pls fix the chrome extension links in the chrome web store.

Signed By
Aman Gupta

**Comment by amangupta00** [comment]
found another issue which has the same agenda and it is solved 
kindly check this issue page https://github.com/subhra74/xdm/issues/39

Use this link for chrome addon : https://chrome.google.com/webstore/detail/xtreme-download-manager/dkckaoghoiffdbomfbbodbbgmhjblecj/

**Comment by OptimusPrime100** [comment]
The ablr

> found another issue which has the same agenda and it is solved kindly check this issue page #39
> 
> Use this link for chrome addon : https://chrome.google.com/webstore/detail/xtreme-download-manager/dkckaoghoiffdbomfbbodbbgmhjblecj/

This link also doesn't work. Please make the extension available as it is hampering the workflow of many people. Thanks in advance.

**Comment by faraidoon123** [comment]
extension is not working but the case is closed when open the link it give error 404

**Comment by tr1ms** [comment]
chrome extenson link not working... gives 404
