### ISSUE TITLE
Download doesn't resume

### ISSUE THREAD

**Issue by Blackwatch1910** [subhra74/xdm#209]
Download doesn't resume even after refresh link is accepted

**Describe the bug**
When refresh link is clicked, the new download link is accepted, but the download doesn't resume.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'refresh link'
2. Click on 'download the link with xdm extension'
3. The link is accepted
4. Nothing really happens

**Expected behavior**
The download should resume.

**Screenshots**
![Screenshot from 2020-05-30 12-33-20](https://user-images.githubusercontent.com/34421869/83322120-c4cd9400-a272-11ea-8e6f-968fd35366da.png)
![Screenshot from 2020-05-30 12-33-16](https://user-images.githubusercontent.com/34421869/83322122-c6975780-a272-11ea-812b-b8bd4b50a772.png)
![Screenshot from 2020-05-30 12-33-11](https://user-images.githubusercontent.com/34421869/83322123-c7c88480-a272-11ea-86e2-2a306947d508.png)

**please complete the following information:**
 - Ubuntu 20.04: [e.g. Linux/Windows]
 - Brave Browser [e.g. chrome, Firefox]
 - XDM addon Version [2.0]
 - XDM Version [7.2.10]

**Generated log using below method**
 - https://github.com/subhra74/xdm/wiki/Generate-log-for-troubleshooting

**Comment by subhra74** [comment]
Please use version 7.2.11
