### ISSUE TITLE
Download Packages with Ambiguous Names

### ISSUE THREAD

**Issue by quarky42** [subhra74/xdm#229]
**Describe the bug**
You have a release called: "xdmsetup.msi"  and another one called "xdm-setup.msi" with two different file sizes.   This is ambiguous.  Please name the download packages something like xdmsetup_x86.msi and xdmsetup_x64.msi if the difference between them is 32bit vs 64bit for example.  If the difference between them is something else, please identify it clearly in the file name.

**To Reproduce**
Go to the release section and be confused by the two file names where one has a hyphen and the other one doesn't.

**Expected behavior**
I expect filenames / downloads to be clearly identified so that when there is more than one it is easy to tell which one is which.

**Screenshots**
Not Applicable.

**please complete the following information:**
Not Applicable.  This all applies to the current release section on GitHub.

**Generated log using below method**
Not Applicable.

**Additional context**
Not Applicable.

**Comment by subhra74** [comment]
That executable is a temporary patched version for a ffmpeg bug, it will be removed. The recommended way to download is from the main page
