### ISSUE TITLE
XDM Downloads stuck at 0%

### ISSUE THREAD

**Issue by MMiano** [subhra74/xdm#246]
XDM downloads stuck at 0% after selecting an option from the XDM browser monitor. Currently using XDM v7.2.11 on Windows 10. Previously tried to upgrade form 7.2.10 to 7.2.11 in hopes that it might resolve it as well as reinstalling but no luck. Tried on both chrome and Firefox to make sure it wasn't an extension problem. Any help would appreciated. It also useful to note that progress window is not closing when pressing exit button. have had to terminate the window via task manager.

**Comment by MikeSamurai** [comment]
This happens when xdm can't capture correctly the download you want.Try reloading the page where your download is and let it load completely before selecting to download from the XDM browser monitor.It has happened to me and it works.

**Comment by mr-kaysar** [comment]
Having download issue in windows 10 Please see the attached image
![xdm_download_issue](https://user-images.githubusercontent.com/53224634/86887908-23601a80-c11b-11ea-85cb-eaf9d6f7871e.png)

**Comment by subhra74** [comment]
> XDM downloads stuck at 0% after selecting an option from the XDM browser monitor. Currently using XDM v7.2.11 on Windows 10. Previously tried to upgrade form 7.2.10 to 7.2.11 in hopes that it might resolve it as well as reinstalling but no luck. Tried on both chrome and Firefox to make sure it wasn't an extension problem. Any help would appreciated. It also useful to note that progress window is not closing when pressing exit button. have had to terminate the window via task manager.

Please share the log and other required details as mentioned in issue template. Without details it is not possible to deduce what is causing the problem

**Comment by MMiano** [comment]
> 
> 
> > XDM downloads stuck at 0% after selecting an option from the XDM browser monitor. Currently using XDM v7.2.11 on Windows 10. Previously tried to upgrade form 7.2.10 to 7.2.11 in hopes that it might resolve it as well as reinstalling but no luck. Tried on both chrome and Firefox to make sure it wasn't an extension problem. Any help would appreciated. It also useful to note that progress window is not closing when pressing exit button. have had to terminate the window via task manager.
> 
> Please share the log and other required details as mentioned in issue template. Without details it is not possible to deduce what is causing the problem

How would I collect such log files in windows. Where would I find them? The best I can do right now is collect some images of the problem.

**Comment by subhra74** [comment]
> > > XDM downloads stuck at 0% after selecting an option from the XDM browser monitor. Currently using XDM v7.2.11 on Windows 10. Previously tried to upgrade form 7.2.10 to 7.2.11 in hopes that it might resolve it as well as reinstalling but no luck. Tried on both chrome and Firefox to make sure it wasn't an extension problem. Any help would appreciated. It also useful to note that progress window is not closing when pressing exit button. have had to terminate the window via task manager.
> > 
> > 
> > Please share the log and other required details as mentioned in issue template. Without details it is not possible to deduce what is causing the problem
> 
> How would I collect such log files in windows. Where would I find them? The best I can do right now is collect some images of the problem.

When you are creating the issue, you are supposed to check the issue template first, which mention how to look for existing similar issues and how to generate logs.


![image](https://user-images.githubusercontent.com/8403090/87884470-a718e180-ca0e-11ea-9638-f1873f51a5bf.png)

[https://github.com/subhra74/xdm/wiki/Generate-log-for-troubleshooting](url)

I understand generating logs might not be very easy for non technical users, I will provide a feature in future to generate logs from XDM itself.

**Comment by MMiano** [comment]
Description of the bug:

'Show Progress' window freezes at 0% for every video selected by the user from the XDM browser monitor(located bottom right of the screen). Subsequently any attempt by the user to try to close(using the close button located adjacent to the minimize button) the "Show progress" window by the user proves futile as the window is permanently stuck on the screen indefinitely. This has resulted in terminating the program using the task manager. 

Steps to produce the behavior:

1. Go to any webpage that has a video.

2. Click of the XDM browser monitor window and select a video.

![Screenshot 1](https://user-images.githubusercontent.com/57748897/88450660-5685f780-ce05-11ea-8384-710b94dee00f.png)
![Screenshot 2](https://user-images.githubusercontent.com/57748897/88450664-5ede3280-ce05-11ea-9656-db3f62055a17.png)

3. The progress bar pops up and gets stuck at 0% indefinitely.(As earlier stated any attempts to close using the provided button the window fail).

![Screenshot 3](https://user-images.githubusercontent.com/57748897/88450670-6c93b800-ce05-11ea-9d37-8a27de53ec98.png)

4. list of videos all stuck at 0% resulting from the bug.

![Screenshot 4](https://user-images.githubusercontent.com/57748897/88450680-87fec300-ce05-11ea-833d-9b89a4e09db0.png)

Expected behavior:

- Once a video is selected from and the user clicks on the "Download Now", the download should progress smoothly from 0% to 100% if they're no external factors affecting it such as unexpected power off. The "show progress" window should not persist indefinitely when user clicks on close button(it shouldn't freeze permanently). 


Specifications:

OS: Windows 10 Home version 1909(OS build 18363.418)

Browser: Firefox version 78.0.2(64-bit).

XDM: version 7.2.11 with AdoptOpenJDK 11.0.6

XDM addons: version 2.1, last updated July 25, 2020.

Logs:

![Screenshot 5](https://user-images.githubusercontent.com/57748897/88450754-2be86e80-ce06-11ea-91b3-e834cb2038b4.png)
![Screenshot 6](https://user-images.githubusercontent.com/57748897/88450759-2ee35f00-ce06-11ea-9dde-909b259aa148.png)

![Screenshot 7](https://user-images.githubusercontent.com/57748897/88450761-2f7bf580-ce06-11ea-90de-cfcc836b70d5.png)
![Screenshot 8](https://user-images.githubusercontent.com/57748897/88450762-30ad2280-ce06-11ea-92e3-d13ad061aa0f.png)
![Screenshot 9](https://user-images.githubusercontent.com/57748897/88450764-3276e600-ce06-11ea-823b-990965f6bff4.png)
![Screenshot 10](https://user-images.githubusercontent.com/57748897/88450765-33a81300-ce06-11ea-90af-237f8717e300.png)
![Screenshot 11](https://user-images.githubusercontent.com/57748897/88450798-7ec22600-ce06-11ea-82af-dc8c31650b55.png)
![Screenshot 12](https://user-images.githubusercontent.com/57748897/88450808-8c77ab80-ce06-11ea-98fa-9d410958859b.png)
![Screenshot 13](https://user-images.githubusercontent.com/57748897/88450812-99949a80-ce06-11ea-86e5-19d909c5c7dd.png)

**Comment by MMiano** [comment]
Managed to solve the issue during log collection:

Apparently config, download and queue files had C:\Users\marti\.xdman\temp rather than C:\Users\Miano\.xdman\temp hence were pointing to an Non-existent user as I had deleted to marti user. Problem Solved, Thank you.

![Screenshot (23)](https://user-images.githubusercontent.com/57748897/88450876-348d7480-ce07-11ea-8ba6-5286b27272ae.png)

**Comment by SubhadipDatta** [comment]
Facing the same issue with the latest version. Running well on my one PC but not on another pc. I installed JDK also.

**Comment by Hamzagm** [comment]
Facing same issue as stated above... My user name is "САМИНА ХАМИИД" but in .config file it shows as "?????? ??????"... I did correct my name & saved the file in unicode coding, instead of ANSI... but when XDM starts it changes it back to "?????? ??????"... 
I can't change my user name, kindly guide me around....
![Screenshot 2022-06-10 160445](https://user-images.githubusercontent.com/107283504/173162012-90169133-1e49-4233-b7c7-8fb8ce5e31f7.png)
