### ISSUE TITLE
Cannot install xdm on raspbian

### ISSUE THREAD

**Issue by fumigawa** [subhra74/xdm#27]
I'm trying to install xdm on Raspberry Pi 3 model B with a latest rsapbian system (Version: September 2019).
I know that rspbian is a 32-bit debian base system (Kernel version: 4.19), so I downloaded 32-bit linux version of xdm and executed it with the command:
`sudo ./install.sh`

But it just come back with this error:
`pi@raspberrypi:~ $ sudo ./install.sh`
`Initializing setup...`
`Extracting files...`
`Unpacking  /opt/xdman/jre/lib/charsets.pack...`
`./install.sh: line 16: /opt/xdman/jre/bin/unpack200: cannot execute binary file: Exec format error`
`Failed to unpack /opt/xdman/jre/lib/charsets.pack`
`Installation aborted`

I'm just a freshman to linux, hope I can get any help. 
Thank you.

**Comment by subhra74** [comment]
You can try by first installing java on your Raspberry Pi.
Then download the jar from [http://xdman.sourceforge.net/xdman.jar](url)
then try running the jar using java -jar xdman.jar
