### ISSUE TITLE
Downloaded audio and video data is converted to mp4 as it is with the same quality without re-encoding

### ISSUE THREAD

**Issue by candrapersada** [subhra74/xdm#286]
add features, Downloaded audio and video data is converted to mp4 as it is with the same quality without re-encoding from xdm.
issues #188

**Comment by subhra74** [comment]
It has been already mentioned that in some cases its not possible to do without reencoding. XDM tries its best to keep the same quality while re encoding

**Comment by subhra74** [comment]
It has been already mentioned that in some cases its not possible to do without reencoding. XDM tries its best to keep the same quality while re encoding

**Comment by candrapersada** [comment]
Then how to make and save new preset reencoding to xdm?
![a](https://user-images.githubusercontent.com/36833664/89382091-661a1000-d724-11ea-8879-a925acf36079.PNG)
