### ISSUE TITLE
Option to close XDM instead of minimizing when clicking cross

### ISSUE THREAD

**Issue by SS-035** [subhra74/xdm#300]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Is there any option to strictly close the application when I click the cross button? Currently it does not closes but instead minimizes. If there is not, then such an option would be helpful. I am using it in Ubuntu.

**Comment by subhra74** [comment]
You can use File->Exit

**Comment by SS-035** [comment]
My bad. I thought it does the same as clicking the cross. Thanks.
