### ISSUE TITLE
Problem with filename character encoding

### ISSUE THREAD

**Issue by Skinner11** [subhra74/xdm#308]
Even with filenames not containing any unusual characters, XDM replaces some chars with weird symbols:

![kép](https://user-images.githubusercontent.com/24269783/90882067-a4156600-e3ab-11ea-8f43-62d78deb05d9.png)
![kép](https://user-images.githubusercontent.com/24269783/90882099-b0012800-e3ab-11ea-802c-8fed7f16ea51.png)

 - OS: Windows 10
 - Firefox
 - XDM addon Version 2.1
 - XDM Version 7.2.11

**Comment by subhra74** [comment]
This is a known issue, will be fixed in future releases
