### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by 1917JOHNNY** [subhra74/xdm#309]
## Checklist

- [ ] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

之前下载安装过XDM为了升级把旧版本卸载了。但卸载后发现就无法安装了新旧版本我都试了都无法安装，显示错误。

![QQ截图20200822012435](https://user-images.githubusercontent.com/64939435/90917995-803b3a00-e416-11ea-9c4c-a699316c829c.png)
![QQ截图20200822012456](https://user-images.githubusercontent.com/64939435/90918016-8b8e6580-e416-11ea-919f-619bac4694e5.png)

**Comment by subhra74** [comment]
Please try to uninstall all versions of XDM, restart and try to install again
