### ISSUE TITLE
gpl2Plus or gpl2Only ?

### ISSUE THREAD

**Issue by SCOTT-HAMILTON** [subhra74/xdm#320]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hello, I'm packaging xtreme-downloader-mangager for Nix see here https://github.com/NixOS/nixpkgs/pull/96861. And one [convention](https://discourse.nixos.org/t/lib-licenses-gpl3-co-are-now-deprecated/8206) for package maintainers is to follow the gnu [recommandations](https://www.gnu.org/licenses/identify-licenses-clearly.html) regarding gpl licenses which is to specify if the software is released under ?gpl?Only or ?gpl?Plus license. Since I'm not sure what you've chosen, I prefer asking you directly this question here.

**Comment by subhra74** [comment]
Licence used here is: GNU General Public License v2.0

**Comment by SCOTT-HAMILTON** [comment]
Thanks (sorry for the long delay) !
