### ISSUE TITLE
Download  complete dialog not showing when disabling Download progress dialog

### ISSUE THREAD

**Issue by ZerGo0** [subhra74/xdm#333]
**Describe the bug**
The Download complete dialog is not showing when disabling the Download progress dialog.

**To Reproduce**
1. Disable "Show download progress window"
2. Enable "Show download complete dialog"
3. Download something and wait till it is completed
4. No window will pop up

**Expected behavior**
The DOwnload complete window should appear.

**please complete the following information:**
 - OS: Windows 10 (Build 2004)
 - Browser Vivaldi
 - XDM addon Version 2.1
 - XDM Version 7.2.11

**Comment by 8227846265** [comment]
I'm having the same issue as well.
