### ISSUE TITLE
Show Arabic file names in strange symbols!

### ISSUE THREAD

**Issue by hamdy989** [subhra74/xdm#358]
When downloading files with Arabic names, they always appear as strange symbols!
But the files work without problems.

**Screenshots**
https://k.top4top.io/p_17403z1rv1.jpg

 - OS: [Windows 10 pro Build 18363 64-bit Arabic]
 - Browser: [chrome v85.0.4183.121 64-bit]
 - XDM addon Version: [2.1]
 - XDM Version: [7.2.11]

**Comment by bon-ami** [comment]
duplicate to https://github.com/subhra74/xdm/issues/143

**Comment by objectProgrammer** [comment]
Fix waiting for merge at #394
