### ISSUE TITLE
No tray icon on ubuntu

### ISSUE THREAD

**Issue by Aikatsui** [subhra74/xdm#359]
**Describe the bug**
The tray icon doesn't appear on ubuntu 20.04.01 even after enabled and restarted. I also use dash to panel extension.

Version 7.2.11 with Java Eclipse OpenJ9 11.0.6 on Linux

**Comment by vinibortoletto** [comment]
I'm having the same problem in Ubuntu.

**Comment by Aikatsui** [comment]
> I'm having the same problem in Ubuntu.

22.04
