### ISSUE TITLE
Download file with non-English character name

### ISSUE THREAD

**Issue by alient12** [subhra74/xdm#377]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running xdm latest version
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

I think XDM doesn't support UTF-8  Unicode, because when I download a file with Persian name, name of the file will change to something like this "ÙØ¯Ø§Ø±ÙØ§Û Ø³Ù ÙØ§Ø².pdf".
Dear Developer please add non-English character support feature to XDM .
sorry for my bad English :) .

**Comment by objectProgrammer** [comment]
I've fixed this in #394, waiting for merge.
