### ISSUE TITLE
With  garbled

### ISSUE THREAD

**Issue by anwar211** [subhra74/xdm#387]
![image](https://user-images.githubusercontent.com/61727188/98784170-ae3c8300-2435-11eb-839e-293b1d922956.png)

## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

**Comment by objectProgrammer** [comment]
Fix waiting for merge at #394
