### ISSUE TITLE
problem with Persian file names

### ISSUE THREAD

**Issue by mahdirezaie336** [subhra74/xdm#406]
When i download files with languages like Persian or Arabic, the file name becomes like this:

Ø¢ÙØ§Ø± ÙÙÙØ¯Ø³Û - ÙØµÙ Ûµ - ØªÙØ²ÛØ¹ ÙØ§Û ÙØ¹Ø±ÙÙ Ù¾ÛÙØ³ØªÙ

**Comment by objectProgrammer** [comment]
Hello, there are already 8 issues about this. I've fixed it, just waiting for merge. Please close this issue.

**Comment by mahdirezaie336** [comment]
Okay thanks
