### ISSUE TITLE
Won't find in download video

### ISSUE THREAD

**Issue by sh123469** [subhra74/xdm#407]
I am running Linux Mint 20. Fresh install. Firefox browser. Videodownloadhelper add-in to retrieve URL. XDM 2020 7.2.11. I am not using the browser add-on since using Videodownloadhelper to get URL. 
Hardware is Dell T-1600 Professional workstation. Xeon E3-1245, 4GB, intel p3000 graphics.

I get the URL for a video, right click the taskbar icon and choose download video. Download video box pops up with url already in it. I click on find. It should normally go to having a bar sliding across the screen while finding. It just goes blank. The file is an HLS streaming file. The box with its title is still there. But no moving bar and never comes back with a found video or give an error message.

I have this same software installed on my Mint 18.3 system and it is working fine.
I have been using it this way since XDM 2015 with never a problem. I have tried wipe out, reboot, download installation again and install again. Still same. Everything else seems to work fine from what I can tell.

I have attached error information. I hope this is an easy fix. I really like this download manager.

[xdm error.txt](https://github.com/subhra74/xdm/files/5585994/xdm.error.txt)

Thank you

**Comment by subhra74** [comment]
XDM is not meant to be used this way, however you can try downloading a latest version of youtube-dl and and put it in %USEPROFILE\.xdman% folder (for windows)
