### ISSUE TITLE
xdm error in Raspbian Buster running in raspberry pi 4 error when running xdman : /usr/bin/xdman: line 5: /opt/xdman/jre/bin/java: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by nepamuceno** [subhra74/xdm#408]
**PLEASE DO NOT JUST SAY "It does not work, or something not working etc." Provide enough relevent details so that the issue can be analyzed and reproduced easily**

**Describe the bug**
Raspbian Buster running in raspberry pi 4 error when running xdman : /usr/bin/xdman: line 5: /opt/xdman/jre/bin/java: cannot execute binary file: Exec format error

**To Reproduce**
#after download, tar , and sudo ./install ..
cd xdm*
ls
cat readme.txt
sudo ./install.sh
xdman

**Expected behavior**
Open xdman program, but i think the /opt/xdman/jre/bin/java provided is in:

$ pi@raspberrypi:~/Desktop/xdm-setup-7.2.11 $ file /opt/xdman/jre/bin/java
/opt/xdman/jre/bin/java: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.18, BuildID[sha1]=b841c4a071e6d4e81cdef031c3779ca748b46fd8, not stripped

Its there a possibility to supply (use) a x86-32 version to work with my rpi 4 ?
thanks
**Screenshots**

**please complete the following information:**
 - OS: Raspbian Buster
 - Browser Chrome
 - XDM addon Version None
 - XDM Version [7.2.11]]

**Generated log using below method**
 - https://github.com/subhra74/xdm/wiki/Generate-log-for-troubleshooting

**Additional context**
Need Java 32 support for Raspberry pi 4 SBC 4G RAM running raspbian buster 
Raspbian GNU/Linux 10 \n \l

**Comment by subhra74** [comment]
You can install the jre supported by the distro, use your distro's package manager to install java and launch xdm from command line

**Comment by swap2ag** [comment]
I built the xdm jar successfully in Raspberry pi 4b using open jdk and maven and it is working as expected after downloading ffmpeg and youtube-dl.

@subhra74 Can you tell me how to create the installer for Rpi from it?
