### ISSUE TITLE
XDM not opening on Linux Mint!

### ISSUE THREAD

**Issue by naveedunjum** [subhra74/xdm#41]
**Describe the bug**
The XDM is not opening on my Linux Mint. Upon clicking, it prompts "An older version of XDM is already running". After that it just closes. The browser plugin is however able to parse videos and also can download them.The issue seems to be with opening only.

**Desktop **
 - OS: Mint
 - Browser Firefox

**Comment by subhra74** [comment]
For quick solution, just kill the old xdm process and then start xdm agin.

In terminal type: ps -ef|grep xdman.jar
This will show the existing xdm process
Take that pid and use kill -9 <pid> to kill the process.

For proper fix:  remove all existing xdm installations and reinstall the latest version.

**Comment by naveedunjum** [comment]
I tried killing it, but after i open it for the first time nothing happens. On calling again, it says the same thing.
Tried downloading the newest version xdm 2015, but it has broken dependencies. The openjdk-7 has no candidate for installing, so downloaded default version. The installation remains incomplete, however XDM works. The problem now seems with the firefox addon. The addon isn't loaded because of some connection error. 
And please change the year in the name

**Comment by subhra74** [comment]
Please use xdm 2018. 
Installer does not have any dependency on java
https://sourceforge.net/projects/xdman/files/xdm-2018-x64.tar.xz/download

**Comment by naveedunjum** [comment]
Thanks. But i think i have located the problem. After uninstalling XDMAN, XDMAN still shows in the startup menu. Opening it doesn't do anything. Tryed purging, but that does not find the package. This instance imo is causing other process to wait. If you have any solution, please share
