### ISSUE TITLE
Can download be  detected??

### ISSUE THREAD

**Issue by Trin88** [subhra74/xdm#410]
## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Can XDM (any downloader) download be detected / tracked /surveillance by owner sites by any means?? What if we download with only 1 connection instead of multiple connections to avoid traffic. Do website or servers program for detections of downloads.
Thank You!

**Comment by subhra74** [comment]
I don't think this is possible. However you can always configure your server to disable partial content (206)
