### ISSUE TITLE
mozilla addon bug

### ISSUE THREAD

**Issue by Puneethkethanapalli** [subhra74/xdm#414]
mozilla addon doesnt work. and also the button on the xdm app to provide url to mozilla addon doesnt respond too.

**Comment by Ghanmohan** [comment]
Which Mozilla addon is not working to be specific?

**Comment by Puneethkethanapalli** [comment]
> Which Mozilla addon is not working to be specific?

I'm sorry for bothering, it is working now. Originally I meant 'browser monitoring' addon .
