### ISSUE TITLE
new version

### ISSUE THREAD

**Issue by ALi-Hosseinzad** [subhra74/xdm#423]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bug tracker for similar questions including closed ones

## Question

when released a new version of the app?

**Comment by objectProgrammer** [comment]
Unfortunately, the creator subhra74 has been inactive for 4 months, I don't think anytime soon..

**Comment by subhra74** [comment]
I am planning to release a new version within few months
