### ISSUE TITLE
XMD will not download anything

### ISSUE THREAD

**Issue by SecretAgentAgentX** [subhra74/xdm#43]
I just attempted to download the newest Manjarowise and XDM errored out on me. I
then attempted to download the Manjaro 19.0.2 ISO and XDM would not download it
nor even give me an error. I then closed the browser and had to force close XDM. I
then relaunched the browser and attempted to download the latest Ubuntu to see if
by chance it was just a fluke and it would not download either. I exited the browser
again, forced XDM to close, restarted my system, and then proceeded to try the
Ubuntu download again in Vivaldi-Stable and Vivaldi-Snapshot and in both XDM
Still would not download the ISO. Since this is happening in both browsers I have to
assume the issue is with the XMD desktop companion. I'm using the latest versions
of both Vivaldi browsers on Manjaro KDE 19.0.2 Testing Build. Any help with this
would be greatly appreciated. Thanks

**Comment by subhra74** [comment]
what error you are getting?
If you kill the xdm process, or disable the extension and then try to download with the browser, does the file gets downloaded?

**Comment by SecretAgentAgentX** [comment]
OK after I know this post I'll reenable XDM in the browser and see what error I get.  After creating the bug report here and on Sourcefotge I added a torrent to qBittorrent and it won't download either. I then disabled XDM in Vivaldi and attempted to download a alternative to it and it just sits there not downloading. I have the below thread on the Manjaro forums cause it's beginning to look like a OS issue. Thing is I haven't installed any updates since yesterday morning.

https://forum.manjaro.org/t/i-cannot-download-anything/130166/3

**Comment by SecretAgentAgentX** [comment]
here is the error i get when attempting to download jdownloader.

`Server does not support resuming, please restart the download.`

**Comment by subhra74** [comment]
> here is the error i get when attempting to download jdownloader.
> 
> `Server does not support resuming, please restart the download.`

jdownloader?

Anyway, The error you posted, that appears when the server does not allow resuming and download in multiple chunks. So there is no point downloading that file with XDM. so you can select Do not capture download from this address from new download dialog, when XDM intercepts the download.

If the issue persists even after disabling the XDM extension, then most likely issue is somewhere else.

**Comment by SecretAgentAgentX** [comment]
Yea like I said I figured that, since with or without the extension abled I can't download. Nor are torrents downloading. This has to be a OS issue. Thing before going to bed it was fine. I download both torrents and regular downloads without issue and there have been no updates since yesterday morning.

**Comment by SecretAgentAgentX** [comment]
OK not sure what the issue was, but like I said in my thread on the Manjaro forums I launched Chrome and tested the Manjarowish and the one torrebt and no issue. After that I went back into Vivaldi and did the same test and worked this time. Using Chrome must of fixed the bottleneck or what ever it was, cause all seems good now.
