### ISSUE TITLE
Accents on file name not working well

### ISSUE THREAD

**Issue by Jneonn** [subhra74/xdm#430]
When I download a file with accents in spanish like: "¿Qué", downloaded file name is like : "Â¿QuÃ© "

**Comment by jaewoolf** [comment]
I can see that It's trying to convert the file name UTF8 to ASCII but that's all I know. What is your OS?

**Comment by Jneonn** [comment]
Pop Os 20.10 based on Ubuntu

**Comment by candrapersada** [comment]
Why does the file name change when I start [downloading](https://cdn5.cloud9xx.com/user1342/c751bab1939a2b83020565e1ac242896/EP.954.1080p.mp4?token=4JtE7CV4ai7cBz50Ewna4g&expires=1608335917&id=148999), for example one.mp4 changes to _1 ?
XDM 7.2.11
Google Chrome
Windows 10

**Comment by objectProgrammer** [comment]
This is already fixed but for some reason subhra does not merge it. My pull request is at #394 and there are already about 8 issues about this.

**Comment by objectProgrammer** [comment]
I was going to ask you to close the issue but perhaps subhra will notice it now? I don't know if s/he hasn't seen the pull request or just hasn't merged.

**Comment by candrapersada** [comment]
and why is the missing file extension?
