### ISSUE TITLE
"Downloads" folder keeps recreating itself

### ISSUE THREAD

**Issue by dybdeskarphet** [subhra74/xdm#431]
### Short Info
**PC:** Asus K55VD
**OS:** Xubuntu 20.04
**Browser:** Chrome v87.0.4280.88
**XDMan Version:** 7.2.11

### Problem
I really like XDM, after all, there are no another user-friendly download managers for Linux except XDMan as far as i am concerned. But when I change my download folder and delete the "Downloads" folder, XDM recreates that "Downloads" folder. Interestingly, when I download something, files are not getting saved to "Downloads" but folder is showing up anyway.

I can live with that as it is not causing me any major problem but my system language is not English and It's kinda odd to see two Download folders in the home directory. Does anyone know how to fix this or am I the only one?

![Ekran görüntüsü_2020-12-17_18-51-30](https://user-images.githubusercontent.com/42360077/102510641-e704f300-4098-11eb-9667-0edeaf2fbc75.png)

**Comment by candrapersada** [comment]
I changed the download location by pressing the folder button, but when I download it again without pressing the folder button it will return to ~/Downloads why can this happen?
![image](https://user-images.githubusercontent.com/36833664/109544755-85cab880-7afa-11eb-8a01-d6177351257b.png)
