### ISSUE TITLE
wrong filenameDecode with Garbled Chinese

### ISSUE THREAD

**Issue by hpp0hpp** [subhra74/xdm#448]
**Describe the bug**

here is the response header
![image](https://user-images.githubusercontent.com/54829297/103630340-7ad12d00-4f7c-11eb-986d-c6585762e0ae.png)
**youcansee, decode a wrong filename**
![image](https://user-images.githubusercontent.com/54829297/103630170-4493ad80-4f7c-11eb-8849-b7cdb10a37da.png)

I would suggest using import java.net.URLDecoder.decode(str, "utf-8"); to decode the name.

**Comment by nourserry** [comment]
Noticed this in Arabic filenames as well.
Running latest version on ubuntu 20.04.

**Comment by walwan** [comment]
Possibly fixed by PR #394
