### ISSUE TITLE
XDM Extension : Please accept below conditions to use this extension: 

### ISSUE THREAD

**Issue by graysuit** [subhra74/xdm#465]
```
Xtreme Download Manager - Privacy
Please accept below conditions to use this extension:
To capture downloads from your browser, "XDM browser monitor" extension will collect and send browsing data to XDM (Xtreme Download Manager) application running on you computer.
The data may include URL, internet address, cookies, query parameters, post data, namely all the data that the browser sends to the server when requesting the file.
This data is stored on your local computer until you delete this download from XDM list of downloads. To download a file, XDM re-sends the original download query made by your browser. XDM sends the data only to the server where the browser sent it to, XDM DOES NOT send this data to our servers, or any 3rd party servers.
```
![Capture](https://user-images.githubusercontent.com/54432616/105571175-d0287f00-5d6f-11eb-8aa8-f682c8b14227.PNG)
Respected developer,
Is it necessary ? Isn't it forcefully making us to send data ?

Many apps like firefox allows us to set whether we want to send data or not.

**Comment by cangyin** [comment]
God, damn it!
These are the key data without which XDM cann't download files for you.
XDM does not send the data to its server.
What are you worring about?

**Comment by cangyin** [comment]
你要是中国人，就赶紧关了issue，太丢人了。

**Comment by graysuit** [comment]
> 
> 
> God, damn it!
> These are the key data without which XDM can't download files for you. XDM does not send the data to its server.
> What are you worring about?

`XDM DOES NOT send this data to our servers, or any 3rd party servers.`
lol ! My mistake here. I forgot to read last that sentence. 
Sorry everyone. My laziness time wastes.

@cangyin I am NOT Chinese. I am Pakistani. But anyway I got your point and Am really sorry for above and closing this issue. Thanks so much mate.
