### ISSUE TITLE
Want to Help

### ISSUE THREAD

**Issue by aliglelo** [subhra74/xdm#47]
Hello,
I have been using XDM for about 2 years and I'm very happy by your work.
I am keen of web developing and I have seen that you are re-designing the XDM website.I know you are way more senior than me but if you need any help in Web Development or SEO , I am always ready for help .
Thanks!

**Comment by subhra74** [comment]
Thanks man!
Unfortunately there is not much scope for web development for XDM, But if you are interested in Java development, then you can help by submitting PR for reported issues.

**Comment by aliglelo** [comment]
Its ok bro
NO i have no knowledge of Java...
