### ISSUE TITLE
File Timestamp always change

### ISSUE THREAD

**Issue by Zorin-Dev** [subhra74/xdm#49]
First of all, I want to thank you for your time developing this app.

XDM is always change file date and time from the actual server date and time.

Please add option to keep server timestamp.

Thanks,

**Comment by subhra74** [comment]
This option can be enabled from browser monitoring page
![image](https://user-images.githubusercontent.com/8403090/77160630-08a06200-6aa8-11ea-9b00-33faf4e1e979.png)

**Comment by Zorin-Dev** [comment]
Thank you, for your help and i wish you healthy and happy life.
