### ISSUE TITLE
 A persisnent switch to disable/enable XDM Download Monitor

### ISSUE THREAD

**Issue by FrosT2k5** [subhra74/xdm#494]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running xdm latest version
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

So right now if I am watching youtube or any video then it shows an option on right side below which shows option to download. I am currently using firefox... This feature is nice and handy but it shows up everytime even if I dont want to download. We can turn off xdm brower monitoring by clicking on it but it isnt persistent. Like after I restart firefox its again enabled and I have to turn it off in every session which is a little pain lol. So can there be like a persistent switch in to disable the browser monitoring for a long time and then turning it on later anytime we want?

**Comment by subhra74** [comment]
You can disable it in XDM app itself instead of browser addon

**Comment by FrosT2k5** [comment]
Yeah got it, thanks :)
