### ISSUE TITLE
Download failed

### ISSUE THREAD

**Issue by SCOTT-HAMILTON** [subhra74/xdm#500]
**To Reproduce**
1. Activate xdm addon
2. Open this url https://nationsglory.fr/download

**Expected behavior**
The download starts

**Errors** : 
```
XDM could not download the file as server sent an invalid response.
```

**please complete the following information:**
 - OS: Linux:NixOS
 - Browser chrome:brave
 - XDM addon Version 2.1
 - XDM Version 7.2.11

**Generated log using below method**
 - https://github.com/subhra74/xdm/wiki/Generate-log-for-troubleshooting

**Comment by ClassickTech** [comment]
Hello, how are you using xdm with NixOS? I have to use it through distrobox.
