### ISSUE TITLE
Browser monitoring is disabled

### ISSUE THREAD

**Issue by lang380** [subhra74/xdm#504]
My xdm version is Version 7.2.11 with Java AdoptOpenJDK 11.0.6 on Windows 10...Please make sure XDM is runnning and you have latest version of XDM installed, This addon is compatible with XDM 7.0 or higher 
What can i do?

**Comment by owl4ce** [comment]
Same issue here

**Comment by shrey43** [comment]
Same issue with me

**Comment by shrey43** [comment]
Hi! I just went to google chrome extension  and downloaded the new one it's working fine

**Comment by owl4ce** [comment]
Fixed in Brave
**Version 1.21.74 Chromium: 89.0.4389.72 (Official Build) unknown (64-bit)**
