### ISSUE TITLE
problems using proxy settings

### ISSUE THREAD

**Issue by FXCNN** [subhra74/xdm#52]
when configuring proxy use, it returns the user and password as if it were mistyped

**Comment by subhra74** [comment]
Can you please explain the issue in detail

**Comment by FXCNN** [comment]
> Can you please explain the issue in detail

I'm sorry language is a barrier for me.
When setting up proxy navigation, the download process does not work, because the username and password do not work. 
It's like I'm typing wrong, and I'm not

**Comment by subhra74** [comment]
What kind of proxy are you using? Is it a corporate proxy at office or something like that? The reason why I am asking is proxy could use different mechanisms for authentication, all of which might not be supported at the moment (NTLM, Negotiate, Digest authentication)

**Comment by FXCNN** [comment]
the proxy uses basic authentication, the previous version worked perfectly (7.2.8) The problem has appeared since I upgraded to version 7.2.10.
I use linux mint 19.3

**Comment by subhra74** [comment]
ok, i will check. but there has been no code changes related to proxy authentication, so its little bit strange.

**Comment by FXCNN** [comment]
You're right, I've tried other PCs and it works fine. 
Thank you for your time.
