### ISSUE TITLE
Youtube bar download does not disappear after closing browser

### ISSUE THREAD

**Issue by raza13** [subhra74/xdm#54]
whether it is Firefox or chrome after closing browser the downloading bar youtube which appear on sites does not disappear after closing browser basically it remains in that position and has to close manually

**Comment by subhra74** [comment]
From version 7.2.10 you can view the captured video list in browser itself:
![77197685-ec231a80-6ae5-11ea-8315-fd4e1c807b9f](https://user-images.githubusercontent.com/8403090/77198753-e7f7fc80-6ae7-11ea-9c9d-ed2b276894b5.png)
To do that uncheck below checkbox:
![77197895-44f2b300-6ae6-11ea-8b7f-ad6f6ec32d7e](https://user-images.githubusercontent.com/8403090/77198790-f7774580-6ae7-11ea-8b14-b6f72847c382.png)

**Comment by raza13** [comment]
thnx sir u save my day

**Comment by FXCNN** [comment]
I always have my browser open (firefox), but I don't like 'DOWNLOAD VIDEO' .

**Comment by raza13** [comment]
me also

**Comment by candrapersada** [comment]
how to close automatically or clear items automatically after use?
![image](https://user-images.githubusercontent.com/36833664/77217221-60e06e00-6b53-11ea-91cc-a58e7962a609.png)
![77198753-e7f7fc80-6ae7-11ea-9c9d-ed2b276894b5](https://user-images.githubusercontent.com/36833664/77217224-65a52200-6b53-11ea-9b8b-139da91f2351.png)

**Comment by subhra74** [comment]
https://user-images.githubusercontent.com/8403090/77198790-f7774580-6ae7-11ea-8b14-b6f72847c382.png

for hiding the DOWNLOAD VIDEO bar.
Clearing items needs to be manually

**Comment by candrapersada** [comment]
auto close
![panel download (1)](https://user-images.githubusercontent.com/36833664/77224843-05869e00-6b9c-11ea-96a0-6a44b2be2966.gif)

**Comment by subhra74** [comment]
auto close is not supported

**Comment by joselmm** [comment]
> how to close automatically or clear items automatically after use? ![77217221-60e06e00-6b53-11ea-91cc-a58e7962a609](https://user-images.githubusercontent.com/36833664/77217285-e19f6a00-6b53-11ea-8e0c-c8a0e5dc6c00.png) ![77198753-e7f7fc80-6ae7-11ea-9c9d-ed2b276894b5](https://user-images.githubusercontent.com/36833664/77217294-eb28d200-6b53-11ea-9ef6-0b28afd70453.png)

with [my edited version of XDM](https://github.com/subhra74/xdm/issues/1162), when clicking "Clear Items" automatticly "DOWNLOAD VIDEO" closes too.

**Comment by edge07chaos** [comment]
For me it's just not working, I can't download any videos
