### ISSUE TITLE
disable DOWNLOAD VIDEO button

### ISSUE THREAD

**Issue by Pechaos** [subhra74/xdm#547]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

is there an option to disable the "DOWNLOAD VIDEO" popup button?
I don't want it to appear every time I open a video on the browser.

**Comment by freezboltz** [comment]
In setting `check` the box `disable floating 'DOWNLOAD VIDEO' popup`

**Comment by ameaninglessname** [comment]
> 
> 
> In setting `check` the box `disable floating 'DOWNLOAD VIDEO' popup`

I've checked that, and I still get the popup. Why?

![image](https://user-images.githubusercontent.com/20263103/132092388-ea03a6fd-dacf-4afb-81a5-be5fe5055e1e.png)

**Comment by subhra74** [comment]
Its not video download popup, this is normal download prompt which is supposed to takeover download from browser
