### ISSUE TITLE
[FEATURE] prevent device sleep

### ISSUE THREAD

**Issue by graysuit** [subhra74/xdm#621]
**FEATURE REQUEST:**
Make xdm to have checkbox with text **"prevent sleep"**, which will then prevent pc from sleeping.

**Background:**
Sometimes, I'm downloading huge file, and I do leave pc and do some other work. But when I return back, I see download chunk was same as before because pc gone in sleep and XDM wasn't able to download.

THANKS

**Comment by NevGi-cpu** [comment]
There is already a feature to prevent hibernation or sleep during downloads. 
Go to Tools > Options > Advance Setting > Prevent Hibernate or Sleep during downloads
 Just tick the checkbox [Image](https://prnt.sc/1i3em0s)

**Comment by graysuit** [comment]
@NevGi-cpu  Thanks a lot. I found that option with your help.
