### ISSUE TITLE
32 segments per download

### ISSUE THREAD

**Issue by ShairiLeh** [subhra74/xdm#65]
Hi Mr. Subhra,

I noticed that when XDM is downloading, it takes quite some time to get 32 segments per download thus downloading process become slower. Is it possible to create additional connections all at once?

**Comment by subhra74** [comment]
It's not possible. XDM dynamically creates the segments, and it depends on many factors like server capability etc, which is necessary for error free smooth downloads. Also increasing download segments does not always means faster download.

**Comment by ShairiLeh** [comment]
Thank you for your explanations Mr. Subhra :)
