### ISSUE TITLE
XDM freezes at 99%

### ISSUE THREAD

**Issue by graysuit** [subhra74/xdm#68]
**Freezes at 99%**
Whenever I download an large file like up to 500 MB or 1000 MB,
It freezes at 99% without any error.
And when I pause and resume it then,
It works fine,

**To Reproduce**

**Expected behavior**
It should not freeze,
It should complete the download without freezing at 99%,

**Desktop **
 - OS: Tested on both win7 + win10
 - Browser firefox
 - Version Latest and Old version

**Additional context**
And sometimes it also freezes any where when file is large,

Thanks for making XDM,
I love XDM,
I prefer people to use it as it is more powerfull than IDM
Thank you.

**Comment by subhra74** [comment]
Can you please generate the generate the logs using method mentioned below:
https://github.com/subhra74/xdm/wiki/Generate-log-for-troubleshooting

**Comment by graysuit** [comment]
OK I will and then let you know

**Comment by graysuit** [comment]
Here I have uploaded all the logs,
https://gist.githubusercontent.com/graysuit/eaa616184bddc7e6c61bf98459eca3c4/raw/59ffa6b60b5d8c37d4817a0aface3ca3dcfbd9b7/freezes-at-99%2525-XDM-logs.txt



But this times it didn't freezed at 99%,
But this problems always comes that,
It freezes at a point So that when I pause and then resume then It works fine.

**Comment by subhra74** [comment]
Thanks for making the effort and sharing the logs, but as you mentioned why the download stops at 99% is could not be analyzed from this log. However I will check the source and try to reproduce the issue. Also if you can reproduce the same with logs, please do share them, they will help to pinpoint where and what is causing the problem. Does this happens with all downloads or only specific servers.

**Comment by ali-libre** [comment]
i have same problem
i have to stop and start download to complete theme.

**Comment by graysuit** [comment]
Sir @subhra74,
This does not happened on specific servers,
And also it does not happened every time.

This problem arises sometimes,
Mostly when file is huge like up to 500 MBs.

Download may sometimes also stops at anytime,
But mostly on 99%.

Thanks for being in touch,
I will try to add more logs.

Sir If you can give me the minimal source code of XDM,
I can convert it to Visual Basic or C#,
Because Java is not recommended over C#/VB in Windows.
As  C#/VB has a lot of libraries builtin in .net framework and .net core in windows.
I am good in VB, I can contribute to it .

**Comment by subhra74** [comment]
I never had that issue, so not able to reproduce/debug as off now. XDM runs on Linux and Mac also. Maintaining multiple code base is not easy, hence Java.

**Comment by graysuit** [comment]
Yeah you are right,
There a lot of code lines and platforms,
So it will be difficult for programmers to filter and re arrange. 

My suggestion here is,
Make the XDM always try pause and resume if downloading is stuck for some time,
Which I do manually to fix this problem,
I know it will solve this problem until we get acknowledge which thing is causing this problem.

And secondly,
I seen that XDM is using portable java to run,
And also I seen its code,
Memory usage can be reduced if you use VB/C#,
Because these are recommended for windows,
OR just give me minimal code of XDM,
I will convert it to VB and test and put it for windows.

**Comment by graysuit** [comment]
By the way after some months with new release,
this problem gone,
I think this is because of internet connectivity problem,
When internet disconnect it don't check for again for connectivity,
So my suggestion here will be to make an function ,
That would start if internet disconnects and check again and again for again connecting to resume.

**Comment by graysuit** [comment]
Issue still exists. So I want to report again with details. Sorry for delay.
I see deadlock here 
```
[ 20a1d202-4111-413a-a544-67a89f8568d4 ] Total inactive chunks: 0
[ 20a1d202-4111-413a-a544-67a89f8568d4 ] List updated
[ 20a1d202-4111-413a-a544-67a89f8568d4 ] Total inactive chunks: 0
[ d016a16b-c607-474a-bd3c-31ef89375163 ] List updated
[ d016a16b-c607-474a-bd3c-31ef89375163 ] Total inactive chunks: 0
[ d016a16b-c607-474a-bd3c-31ef89375163 ] List updated
[ d016a16b-c607-474a-bd3c-31ef89375163 ] Total inactive chunks: 0
[ d016a16b-c607-474a-bd3c-31ef89375163 ] List updated
[ d016a16b-c607-474a-bd3c-31ef89375163 ] Total inactive chunks: 0
[ 20a1d202-4111-413a-a544-67a89f8568d4 ] List updated
[ 20a1d202-4111-413a-a544-67a89f8568d4 ] Total inactive chunks: 0
[ c9943796-5774-4bad-9e98-f3371895337a ] List updated
[ c9943796-5774-4bad-9e98-f3371895337a ] Total inactive chunks: 0
[ c9943796-5774-4bad-9e98-f3371895337a ] List updated
[ c9943796-5774-4bad-9e98-f3371895337a ] Total inactive chunks: 0
[ d016a16b-c607-474a-bd3c-31ef89375163 ] List updated
[ 20a1d202-4111-413a-a544-67a89f8568d4 ] List updated
[ d016a16b-c607-474a-bd3c-31ef89375163 ] Total inactive chunks: 0
[ 20a1d202-4111-413a-a544-67a89f8568d4 ] Total inactive chunks: 0
[ b8af1b19-b7f6-48a3-b953-8a4dceba29ef ] List updated
[ b8af1b19-b7f6-48a3-b953-8a4dceba29ef ] Total inactive chunks: 0
[ d016a16b-c607-474a-bd3c-31ef89375163 ] List updated
[ d016a16b-c607-474a-bd3c-31ef89375163 ] Total inactive chunks: 0
[ 20a1d202-4111-413a-a544-67a89f8568d4 ] List updated
[ 20a1d202-4111-413a-a544-67a89f8568d4 ] Total inactive chunks: 0
[ d016a16b-c607-474a-bd3c-31ef89375163 ] List updated
[ d016a16b-c607-474a-bd3c-31ef89375163 ] Total inactive chunks: 0
[ d016a16b-c607-474a-bd3c-31ef89375163 ] List updated
[ d016a16b-c607-474a-bd3c-31ef89375163 ] Total inactive chunks: 0
[ d016a16b-c607-474a-bd3c-31ef89375163 ] List updated
[ d016a16b-c607-474a-bd3c-31ef89375163 ] Total inactive chunks: 0
[ 20a1d202-4111-413a-a544-67a89f8568d4 ] List updated
[ 20a1d202-4111-413a-a544-67a89f8568d4 ] Total inactive chunks: 0
[ d016a16b-c607-474a-bd3c-31ef89375163 ] List updated
[ 20a1d202-4111-413a-a544-67a89f8568d4 ] List updated
[ d016a16b-c607-474a-bd3c-31ef89375163 ] Total inactive chunks: 0
[ 20a1d202-4111-413a-a544-67a89f8568d4 ] Total inactive chunks: 0
[ 20a1d202-4111-413a-a544-67a89f8568d4 ] List updated
[ 20a1d202-4111-413a-a544-67a89f8568d4 ] Total inactive chunks: 0
[ 20a1d202-4111-413a-a544-67a89f8568d4 ] List updated
[ 20a1d202-4111-413a-a544-67a89f8568d4 ] Total inactive chunks: 0
[ d016a16b-c607-474a-bd3c-31ef89375163 ] List updated
[ d016a16b-c607-474a-bd3c-31ef89375163 ] Total inactive chunks: 0
[ d016a16b-c607-474a-bd3c-31ef89375163 ] List updated
[ d016a16b-c607-474a-bd3c-31ef89375163 ] Total inactive chunks: 0
[ d016a16b-c607-474a-bd3c-31ef89375163 ] List updated
[ d016a16b-c607-474a-bd3c-31ef89375163 ] Total inactive chunks: 0
[ 20a1d202-4111-413a-a544-67a89f8568d4 ] List updated
[ 20a1d202-4111-413a-a544-67a89f8568d4 ] Total inactive chunks: 0
java.net.SocketTimeoutException: Read timed out
[ 20a1d202-4111-413a-a544-67a89f8568d4 ] List updated
        at java.base/java.net.SocketInputStream.socketRead0(Native Method)[ d016
a16b-c607-474a-bd3c-31ef89375163 ] List updated

[ 20a1d202-4111-413a-a544-67a89f8568d4 ] Total inactive chunks: 0
        at java.base/java.net.SocketInputStream.socketRead(Unknown Source)
        at java.base/java.net.SocketInputStream.read(Unknown Source)
        at java.base/java.net.SocketInputStream.read(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket
(Unknown Source)
[ d016a16b-c607-474a-bd3c-31ef89375163 ] Total inactive chunks: 0
        at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(Unknow
n Source)
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(Unknown
Source)
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(Unknown
Source)
        at xdman.util.NetUtils.readLine(NetUtils.java:16)
        at xdman.network.http.XDMHttpClient.connect(XDMHttpClient.java:90)
        at xdman.downloaders.http.HttpChannel.connectImpl(HttpChannel.java:123)
        at xdman.downloaders.AbstractChannel.connect(AbstractChannel.java:44)
        at xdman.downloaders.AbstractChannel.run(AbstractChannel.java:61)
        at java.base/java.lang.Thread.run(Unknown Source)
[ 8857b39f-f6a2-4e77-8aa3-9d0b4b8093c6 ] 8857b39f-f6a2-4e77-8aa3-9d0b4b8093c6
[ 8857b39f-f6a2-4e77-8aa3-9d0b4b8093c6 ] xdman.network.NetworkException: Read ti
med out
        at xdman.network.http.XDMHttpClient.connect(XDMHttpClient.java:126)
        at xdman.downloaders.http.HttpChannel.connectImpl(HttpChannel.java:123)
        at xdman.downloaders.AbstractChannel.connect(AbstractChannel.java:44)
        at xdman.downloaders.AbstractChannel.run(AbstractChannel.java:61)
        at java.base/java.lang.Thread.run(Unknown Source)
[ d016a16b-c607-474a-bd3c-31ef89375163 ] List updated
[ d016a16b-c607-474a-bd3c-31ef89375163 ] Total inactive chunks: 0

```
