### ISSUE TITLE
Ver7.2.10 not support chinese file name(maybe east-asia font)

### ISSUE THREAD

**Issue by logmeoutin** [subhra74/xdm#76]
**Describe the bug**
for example, the orginal file name is "Python编程入门 第3版.pdf",  in XDM "NEW DOWNLOAD" window, it appera as "Pythonç¼ç¨å¥é¨  ç¬¬3ç.pdf" 

**To Reproduce**
1. Go to 'https://tc5.us/file/17342680-312078666'
2. At left corner in this page, you can find word in chinese "普通下载", 
3. below this word, a button named "立即下载“ 。click this button
4. If XDM is running and monitoring browser,  the "NEW DOWNLOAD" dialog will pop up , you can find the incorrent file name in File box. It appears "Pythonç¼ç¨å¥é¨  ç¬¬3ç.pdf" 

**Expected behavior**
I want XDM support chinese file name ,maybe east-asia language  has the same issue.

**Screenshots**
![01](https://user-images.githubusercontent.com/56515892/77729536-e2476d00-7039-11ea-9682-12bfa440fc3d.jpg)
![2](https://user-images.githubusercontent.com/56515892/77729559-ea9fa800-7039-11ea-8110-ce41b249ddc2.png)

**please complete the following information:**
 - OS: Windows7 x64
 - Browser: Firefox 
 - XDM addon Version : not sure, up to date 
 - XDM Version: App version 7.2.10 with runtime 11.0.6

**Generated log using below method**

**Additional context**

**Comment by subhra74** [comment]
i tried the link, but after getting this screen.
![image](https://user-images.githubusercontent.com/8403090/77792617-f060b200-7068-11ea-8cca-29e8775f93dc.png)
Can you please some other direct link

**Comment by objectProgrammer** [comment]
@subhra74 It's not related to fonts. Fonts are only used to display characters, if the font didn't support it would just show a square not garbled data. It's related to the url-decoding algorithm, which I've fixed in #394.
