### ISSUE TITLE
Release the next version of XDM (maybe 7.2.12)

### ISSUE THREAD

**Issue by machitgarha** [subhra74/xdm#760]
First of all, thanks for this great application.

Some of the issues here are created and open, just because of not having a new release to include the patch #394. I think releasing a new version like 7.2.12 would fix all of those issues related to handling of UTF-8 characters.

Would you please publish a new release to cover this?

**Comment by narulmcto** [comment]
It was announced last October, but it hasn't been released yet.

**Comment by machitgarha** [comment]
@subhra74, may I kindly ask you to open an issue regarding a request for a new maintainer? Because, as you know, you don't have any recent activities on GitHub.

**Comment by narulmcto** [comment]
邮件已收到，我会尽快查看

**Comment by machitgarha** [comment]
So this is fixed in the new beta version (8.0.18), thanks for the hard work, @subhra74 and others!

**Comment by narulmcto** [comment]
邮件已收到，我会尽快查看
