### ISSUE TITLE
Not working on Firefox after update.

### ISSUE THREAD

**Issue by pO0P3R125** [subhra74/xdm#80]
So, I used a previous version, and it worked perfectly. Then I updated to 7.2.1 and the latest plugin and suddenly, Firefox will completely refuse to enable browser monitoring (the icon is shown with that red mark). I don't know if it's something in my setup, or just recent changes in Firefox/XDM. To make sure I wasn't doing something wrong, I kept enabling/disabling the plugin, as well as the options for automatic updates/private browsing, made sure to have the latest version of the [plugin](https://addons.mozilla.org/en-US/firefox/addon/xdm-browser-monitor/) and [XDM](https://github.com/subhra74/xdm/releases). Finally, I even reinstalled both XDM and the plugin, so far nothing has worked for me. I would appreciate some help.

 - OS: Windows 10 x64
 - Firefox 74.0 (64-bit)
 - XDM addon 2.1
 - XDM Version 7.2.1

Here's the log too.
![log](https://user-images.githubusercontent.com/43865463/77776557-cd57e300-7013-11ea-940c-f95fcb1c8572.PNG)

**Comment by subhra74** [comment]
are you using any vpn software or proxy? is xdm running when you checked the browser extension?

**Comment by pO0P3R125** [comment]
Yeah that was it! Thanks a lot (it was a vpn)
