### ISSUE TITLE
Can't install XDM

### ISSUE THREAD

**Issue by Eblusk** [subhra74/xdm#806]
Can't install XDM

## Checklist

- [ y] I'm asking a question
- [ y ] I've looked through the README and FAQ for similar questions
- [ y ] I've searched the bugtracker for similar questions including closed ones

## Question

Hi, im new linux user (2 days ago). I have an issue as well a question. I cant install XDM. when I use  ./install.sh , it says command not found. I extracted the file and I tried download other version as well but still the same.

My question is if I succeded install XDM, will it directly be my deafult downloader? because I tried uget but whenever i use it the download is error. If XDM can't be deafult downloader directly, how can i set it? because download using opera deafult download is not that fast.

Thanks in advance.

WRITE QUESTION HERE

**Comment by fynks** [comment]
> Can't install XDM
> ## Checklist
> 
>     * [ y] I'm asking a question
> 
>     * [ y ] I've looked through the README and FAQ for similar questions
> 
>     * [ y ] I've searched the bugtracker for similar questions including closed ones
> 
> 
> ## Question
> 
> Hi, im new linux user (2 days ago). I have an issue as well a question. I cant install XDM. when I use ./install.sh , it says command not found. I extracted the file and I tried download other version as well but still the same.
> 
> My question is if I succeded install XDM, will it directly be my deafult downloader? because I tried uget but whenever i use it the download is error. If XDM can't be deafult downloader directly, how can i set it? because download using opera deafult download is not that fast.
> 
> Thanks in advance.
> 
> WRITE QUESTION HERE

So for installing the xdm successfully make sure you download the latest version and extract the zip folder,then make the install script executable by running `sudo chmod +x 777` then run `./install.sh` and now it should install fine.
Regarding your second question of making it your default downloader,you have to install "xdm browser extension" for your respective browser.i.e from firefox addon store if you use firefox and from google extenaion store if you use chromium based browsers like chrome,edge or opera.
