### ISSUE TITLE
unable to add extension in G-Chrome

### ISSUE THREAD

**Issue by Murugesh-Hobbyist** [subhra74/xdm#903]
when I paste the url
https://subhra74.github.io/xdm/redirect.html?target=chrome
in chrome, im getting

404. That’s an error.
The requested URL was not found on this server. That’s all we [know.]([url](url))

can find the screen shot on 
https://drive.google.com/file/d/1XchmVAu2Yv6cJMpSsmhJGVh9YUVCHtl2/view?usp=sharing
https://drive.google.com/file/d/1XZgBOpS0eOWXwZ-66EZe7KVq_FwR-VB3/view?usp=sharing

Please help to resolve this issue. thanks.

**Comment by yaldadi** [comment]
I have this proble too.

**Comment by rram12** [comment]
I found this link
https://chrome.google.com/webstore/detail/xdm-integration-module-be/akdmdglbephckgfmdffcdebnpjgamofc

**Comment by stevenmukama** [comment]
> I found this link https://chrome.google.com/webstore/detail/xdm-integration-module-be/akdmdglbephckgfmdffcdebnpjgamofc

I used this link but it doesn't work. Please help me i have been trying to find xdm extension in google chrome but i can't find it there.

**Comment by Nopparuj-an** [comment]
Manually download the extension and use the developer mode in chrome extension to install it as a folder.

**Steps**
1. Go here [https://downgit.github.io/#/home?url=https://github.com/subhra74/xdm/tree/master/app/xdm-browser-monitor/chrome](https://downgit.github.io/#/home?url=https://github.com/subhra74/xdm/tree/master/app/xdm-browser-monitor/chrome)
2. unzip the main folder and place the sub-folder somewhere.
3. go to [chrome://extensions/](chrome://extensions/)
4. turn on developer mode
5. click load unpacked
6. select the sub-folder you just unzipped
![image](https://user-images.githubusercontent.com/47713359/194745344-8c8905ad-3147-416d-8a64-fb1ae7691a7c.png)

**Comment by Murugesh-Hobbyist** [comment]
Thanks - [Nopparuj-an](https://github.com/Nopparuj-an)
I can download using the XDM now.
but in the chrome extension, I could see the errors as the attached image links below.
![Screenshot - 09-10-2022 , 11_30_53 PM](https://user-images.githubusercontent.com/75427145/194772446-7475e2d1-63dd-4eea-9241-989968243671.png)
![Screenshot - 09-10-2022 , 11_31_04 PM](https://user-images.githubusercontent.com/75427145/194772448-6fa862f5-c8ee-4a79-a082-42f4dfc890cf.png)

**Comment by MisterSirCode** [comment]
Is this project just abandoned or something?? The developer never seems to respond..

**Comment by Nopparuj-an** [comment]
> Thanks - [Nopparuj-an](https://github.com/Nopparuj-an)
> I can download using the XDM now.
> but in the chrome extension, I could see the errors as the images below.

Ignore it, the extension works fine for now, until chrome update its manifest to version 3.
