### ISSUE TITLE
Uninstall (linux)

### ISSUE THREAD

**Issue by RafaelLinux** [subhra74/xdm#929]
I installed XDM using "install.sh". As it crashed with a lot of JAVA messages, I want to uninstall it .... but HOW?? There is no "uninstaller" in folder next to "install.sh".

Thank you

**Comment by cantalupo555** [comment]
readme.txt

5. To uninstall run /opt/xdman/uninstall.sh as root

**Comment by RafaelLinux** [comment]
Please, add procedure to README for all users.

Thank you
