### ISSUE TITLE
XDM `8.0.12` Beta - Can't download data from `blob:chrome-extension://` protocol

### ISSUE THREAD

**Issue by lamualfa** [subhra74/xdm#940]
# Description

XDM shouldn't capture any download within the `blob:chrome-extension://` protocol. So the browser can handle any download process within that protocol (not blocking the user from downloading).

![image](https://user-images.githubusercontent.com/39755201/205096865-99ec1cd0-eec0-45aa-a0a2-3b2219e2ecb7.png)

# Versions

- XDM 8.0.12 Beta
- [SVG Export Chrome Extension](https://chrome.google.com/webstore/detail/svg-export/naeaaedieihlkmdajjefioajbbdbdjgp)

**Comment by subhra74** [comment]
Please try 8.0.18

**Comment by lamualfa** [comment]
@subhra74 Ok, it's work. Thank you.
